// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: rng.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RandBooleansRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Length uint32 `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
}

func (x *RandBooleansRequest) Reset() {
	*x = RandBooleansRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rng_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RandBooleansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandBooleansRequest) ProtoMessage() {}

func (x *RandBooleansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rng_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandBooleansRequest.ProtoReflect.Descriptor instead.
func (*RandBooleansRequest) Descriptor() ([]byte, []int) {
	return file_rng_proto_rawDescGZIP(), []int{0}
}

func (x *RandBooleansRequest) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type RandBooleansResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []bool `protobuf:"varint,1,rep,packed,name=data,proto3" json:"data,omitempty"`
}

func (x *RandBooleansResponse) Reset() {
	*x = RandBooleansResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rng_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RandBooleansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandBooleansResponse) ProtoMessage() {}

func (x *RandBooleansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rng_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandBooleansResponse.ProtoReflect.Descriptor instead.
func (*RandBooleansResponse) Descriptor() ([]byte, []int) {
	return file_rng_proto_rawDescGZIP(), []int{1}
}

func (x *RandBooleansResponse) GetData() []bool {
	if x != nil {
		return x.Data
	}
	return nil
}

type RandBytesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Length uint32 `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
}

func (x *RandBytesRequest) Reset() {
	*x = RandBytesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rng_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RandBytesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandBytesRequest) ProtoMessage() {}

func (x *RandBytesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rng_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandBytesRequest.ProtoReflect.Descriptor instead.
func (*RandBytesRequest) Descriptor() ([]byte, []int) {
	return file_rng_proto_rawDescGZIP(), []int{2}
}

func (x *RandBytesRequest) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type RandBytesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RandBytesResponse) Reset() {
	*x = RandBytesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rng_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RandBytesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandBytesResponse) ProtoMessage() {}

func (x *RandBytesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rng_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandBytesResponse.ProtoReflect.Descriptor instead.
func (*RandBytesResponse) Descriptor() ([]byte, []int) {
	return file_rng_proto_rawDescGZIP(), []int{3}
}

func (x *RandBytesResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RandIntegersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Min    int32  `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max    int32  `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	Length uint32 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
}

func (x *RandIntegersRequest) Reset() {
	*x = RandIntegersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rng_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RandIntegersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandIntegersRequest) ProtoMessage() {}

func (x *RandIntegersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rng_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandIntegersRequest.ProtoReflect.Descriptor instead.
func (*RandIntegersRequest) Descriptor() ([]byte, []int) {
	return file_rng_proto_rawDescGZIP(), []int{4}
}

func (x *RandIntegersRequest) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *RandIntegersRequest) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *RandIntegersRequest) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type RandIntegersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []int32 `protobuf:"varint,1,rep,packed,name=data,proto3" json:"data,omitempty"`
}

func (x *RandIntegersResponse) Reset() {
	*x = RandIntegersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rng_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RandIntegersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandIntegersResponse) ProtoMessage() {}

func (x *RandIntegersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rng_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandIntegersResponse.ProtoReflect.Descriptor instead.
func (*RandIntegersResponse) Descriptor() ([]byte, []int) {
	return file_rng_proto_rawDescGZIP(), []int{5}
}

func (x *RandIntegersResponse) GetData() []int32 {
	if x != nil {
		return x.Data
	}
	return nil
}

type RandUniformRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Min    float64 `protobuf:"fixed64,1,opt,name=min,proto3" json:"min,omitempty"`
	Max    float64 `protobuf:"fixed64,2,opt,name=max,proto3" json:"max,omitempty"`
	Length uint32  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
}

func (x *RandUniformRequest) Reset() {
	*x = RandUniformRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rng_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RandUniformRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandUniformRequest) ProtoMessage() {}

func (x *RandUniformRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rng_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandUniformRequest.ProtoReflect.Descriptor instead.
func (*RandUniformRequest) Descriptor() ([]byte, []int) {
	return file_rng_proto_rawDescGZIP(), []int{6}
}

func (x *RandUniformRequest) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *RandUniformRequest) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *RandUniformRequest) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type RandUniformResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []float64 `protobuf:"fixed64,1,rep,packed,name=data,proto3" json:"data,omitempty"`
}

func (x *RandUniformResponse) Reset() {
	*x = RandUniformResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rng_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RandUniformResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandUniformResponse) ProtoMessage() {}

func (x *RandUniformResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rng_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandUniformResponse.ProtoReflect.Descriptor instead.
func (*RandUniformResponse) Descriptor() ([]byte, []int) {
	return file_rng_proto_rawDescGZIP(), []int{7}
}

func (x *RandUniformResponse) GetData() []float64 {
	if x != nil {
		return x.Data
	}
	return nil
}

type RandNormalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mean   float64 `protobuf:"fixed64,1,opt,name=mean,proto3" json:"mean,omitempty"`
	Stddev float64 `protobuf:"fixed64,2,opt,name=stddev,proto3" json:"stddev,omitempty"`
	Length uint32  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
}

func (x *RandNormalRequest) Reset() {
	*x = RandNormalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rng_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RandNormalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandNormalRequest) ProtoMessage() {}

func (x *RandNormalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rng_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandNormalRequest.ProtoReflect.Descriptor instead.
func (*RandNormalRequest) Descriptor() ([]byte, []int) {
	return file_rng_proto_rawDescGZIP(), []int{8}
}

func (x *RandNormalRequest) GetMean() float64 {
	if x != nil {
		return x.Mean
	}
	return 0
}

func (x *RandNormalRequest) GetStddev() float64 {
	if x != nil {
		return x.Stddev
	}
	return 0
}

func (x *RandNormalRequest) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type RandNormalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []float64 `protobuf:"fixed64,1,rep,packed,name=data,proto3" json:"data,omitempty"`
}

func (x *RandNormalResponse) Reset() {
	*x = RandNormalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rng_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RandNormalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandNormalResponse) ProtoMessage() {}

func (x *RandNormalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rng_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandNormalResponse.ProtoReflect.Descriptor instead.
func (*RandNormalResponse) Descriptor() ([]byte, []int) {
	return file_rng_proto_rawDescGZIP(), []int{9}
}

func (x *RandNormalResponse) GetData() []float64 {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_rng_proto protoreflect.FileDescriptor

var file_rng_proto_rawDesc = []byte{
	0x0a, 0x09, 0x72, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x73, 0x69,
	0x72, 0x6e, 0x67, 0x22, 0x2d, 0x0a, 0x13, 0x52, 0x61, 0x6e, 0x64, 0x42, 0x6f, 0x6f, 0x6c, 0x65,
	0x61, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65,
	0x6e, 0x67, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67,
	0x74, 0x68, 0x22, 0x2a, 0x0a, 0x14, 0x52, 0x61, 0x6e, 0x64, 0x42, 0x6f, 0x6f, 0x6c, 0x65, 0x61,
	0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x08, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2a,
	0x0a, 0x10, 0x52, 0x61, 0x6e, 0x64, 0x42, 0x79, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x22, 0x27, 0x0a, 0x11, 0x52, 0x61,
	0x6e, 0x64, 0x42, 0x79, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x51, 0x0a, 0x13, 0x52, 0x61, 0x6e, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x67,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x61, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x12, 0x16,
	0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x22, 0x2a, 0x0a, 0x14, 0x52, 0x61, 0x6e, 0x64, 0x49, 0x6e,
	0x74, 0x65, 0x67, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x50, 0x0a, 0x12, 0x52, 0x61, 0x6e, 0x64, 0x55, 0x6e, 0x69, 0x66, 0x6f, 0x72,
	0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61,
	0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x12, 0x16, 0x0a, 0x06,
	0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6c, 0x65,
	0x6e, 0x67, 0x74, 0x68, 0x22, 0x29, 0x0a, 0x13, 0x52, 0x61, 0x6e, 0x64, 0x55, 0x6e, 0x69, 0x66,
	0x6f, 0x72, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x57, 0x0a, 0x11, 0x52, 0x61, 0x6e, 0x64, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x65, 0x61, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x04, 0x6d, 0x65, 0x61, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x64, 0x64,
	0x65, 0x76, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x73, 0x74, 0x64, 0x64, 0x65, 0x76,
	0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x22, 0x28, 0x0a, 0x12, 0x52, 0x61, 0x6e, 0x64,
	0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x32, 0xf4, 0x02, 0x0a, 0x03, 0x52, 0x6e, 0x67, 0x12, 0x4b, 0x0a, 0x0c, 0x52, 0x61,
	0x6e, 0x64, 0x42, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x73, 0x12, 0x1b, 0x2e, 0x70, 0x73, 0x69,
	0x72, 0x6e, 0x67, 0x2e, 0x52, 0x61, 0x6e, 0x64, 0x42, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x73, 0x69, 0x72, 0x6e, 0x67,
	0x2e, 0x52, 0x61, 0x6e, 0x64, 0x42, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x09, 0x52, 0x61, 0x6e, 0x64, 0x42,
	0x79, 0x74, 0x65, 0x73, 0x12, 0x18, 0x2e, 0x70, 0x73, 0x69, 0x72, 0x6e, 0x67, 0x2e, 0x52, 0x61,
	0x6e, 0x64, 0x42, 0x79, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x70, 0x73, 0x69, 0x72, 0x6e, 0x67, 0x2e, 0x52, 0x61, 0x6e, 0x64, 0x42, 0x79, 0x74, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0c, 0x52,
	0x61, 0x6e, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x73, 0x12, 0x1b, 0x2e, 0x70, 0x73,
	0x69, 0x72, 0x6e, 0x67, 0x2e, 0x52, 0x61, 0x6e, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x73, 0x69, 0x72, 0x6e,
	0x67, 0x2e, 0x52, 0x61, 0x6e, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0b, 0x52, 0x61, 0x6e, 0x64,
	0x55, 0x6e, 0x69, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x1a, 0x2e, 0x70, 0x73, 0x69, 0x72, 0x6e, 0x67,
	0x2e, 0x52, 0x61, 0x6e, 0x64, 0x55, 0x6e, 0x69, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x73, 0x69, 0x72, 0x6e, 0x67, 0x2e, 0x52, 0x61, 0x6e,
	0x64, 0x55, 0x6e, 0x69, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x45, 0x0a, 0x0a, 0x52, 0x61, 0x6e, 0x64, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c,
	0x12, 0x19, 0x2e, 0x70, 0x73, 0x69, 0x72, 0x6e, 0x67, 0x2e, 0x52, 0x61, 0x6e, 0x64, 0x4e, 0x6f,
	0x72, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x73,
	0x69, 0x72, 0x6e, 0x67, 0x2e, 0x52, 0x61, 0x6e, 0x64, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rng_proto_rawDescOnce sync.Once
	file_rng_proto_rawDescData = file_rng_proto_rawDesc
)

func file_rng_proto_rawDescGZIP() []byte {
	file_rng_proto_rawDescOnce.Do(func() {
		file_rng_proto_rawDescData = protoimpl.X.CompressGZIP(file_rng_proto_rawDescData)
	})
	return file_rng_proto_rawDescData
}

var file_rng_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_rng_proto_goTypes = []interface{}{
	(*RandBooleansRequest)(nil),  // 0: psirng.RandBooleansRequest
	(*RandBooleansResponse)(nil), // 1: psirng.RandBooleansResponse
	(*RandBytesRequest)(nil),     // 2: psirng.RandBytesRequest
	(*RandBytesResponse)(nil),    // 3: psirng.RandBytesResponse
	(*RandIntegersRequest)(nil),  // 4: psirng.RandIntegersRequest
	(*RandIntegersResponse)(nil), // 5: psirng.RandIntegersResponse
	(*RandUniformRequest)(nil),   // 6: psirng.RandUniformRequest
	(*RandUniformResponse)(nil),  // 7: psirng.RandUniformResponse
	(*RandNormalRequest)(nil),    // 8: psirng.RandNormalRequest
	(*RandNormalResponse)(nil),   // 9: psirng.RandNormalResponse
}
var file_rng_proto_depIdxs = []int32{
	0, // 0: psirng.Rng.RandBooleans:input_type -> psirng.RandBooleansRequest
	2, // 1: psirng.Rng.RandBytes:input_type -> psirng.RandBytesRequest
	4, // 2: psirng.Rng.RandIntegers:input_type -> psirng.RandIntegersRequest
	6, // 3: psirng.Rng.RandUniform:input_type -> psirng.RandUniformRequest
	8, // 4: psirng.Rng.RandNormal:input_type -> psirng.RandNormalRequest
	1, // 5: psirng.Rng.RandBooleans:output_type -> psirng.RandBooleansResponse
	3, // 6: psirng.Rng.RandBytes:output_type -> psirng.RandBytesResponse
	5, // 7: psirng.Rng.RandIntegers:output_type -> psirng.RandIntegersResponse
	7, // 8: psirng.Rng.RandUniform:output_type -> psirng.RandUniformResponse
	9, // 9: psirng.Rng.RandNormal:output_type -> psirng.RandNormalResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rng_proto_init() }
func file_rng_proto_init() {
	if File_rng_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rng_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RandBooleansRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rng_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RandBooleansResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rng_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RandBytesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rng_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RandBytesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rng_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RandIntegersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rng_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RandIntegersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rng_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RandUniformRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rng_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RandUniformResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rng_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RandNormalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rng_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RandNormalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rng_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rng_proto_goTypes,
		DependencyIndexes: file_rng_proto_depIdxs,
		MessageInfos:      file_rng_proto_msgTypes,
	}.Build()
	File_rng_proto = out.File
	file_rng_proto_rawDesc = nil
	file_rng_proto_goTypes = nil
	file_rng_proto_depIdxs = nil
}
