//
// Copyright (C) 2025 NullSpook
//
// This file is part of psirng.
//
// psirng is free software: you can redistribute it and/or modify it under the
// terms of the GNU Affero General Public License as published by the Free
// Software Foundation, either version 3 of the License, or (at your option)
// any later version.
//
// psirng is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for
// more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with psirng.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: rng.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Rng_RandBooleans_FullMethodName              = "/psirng.Rng/RandBooleans"
	Rng_RandBytes_FullMethodName                 = "/psirng.Rng/RandBytes"
	Rng_RandIntegers_FullMethodName              = "/psirng.Rng/RandIntegers"
	Rng_RandUniform_FullMethodName               = "/psirng.Rng/RandUniform"
	Rng_RandNormal_FullMethodName                = "/psirng.Rng/RandNormal"
	Rng_RandBooleansBiasAmplified_FullMethodName = "/psirng.Rng/RandBooleansBiasAmplified"
)

// RngClient is the client API for Rng service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RngClient interface {
	RandBooleans(ctx context.Context, in *RandBooleansRequest, opts ...grpc.CallOption) (*RandBooleansResponse, error)
	RandBytes(ctx context.Context, in *RandBytesRequest, opts ...grpc.CallOption) (*RandBytesResponse, error)
	RandIntegers(ctx context.Context, in *RandIntegersRequest, opts ...grpc.CallOption) (*RandIntegersResponse, error)
	RandUniform(ctx context.Context, in *RandUniformRequest, opts ...grpc.CallOption) (*RandUniformResponse, error)
	RandNormal(ctx context.Context, in *RandNormalRequest, opts ...grpc.CallOption) (*RandNormalResponse, error)
	RandBooleansBiasAmplified(ctx context.Context, in *RandBooleansBiasAmplifiedRequest, opts ...grpc.CallOption) (*RandBooleansBiasAmplifiedResponse, error)
}

type rngClient struct {
	cc grpc.ClientConnInterface
}

func NewRngClient(cc grpc.ClientConnInterface) RngClient {
	return &rngClient{cc}
}

func (c *rngClient) RandBooleans(ctx context.Context, in *RandBooleansRequest, opts ...grpc.CallOption) (*RandBooleansResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RandBooleansResponse)
	err := c.cc.Invoke(ctx, Rng_RandBooleans_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rngClient) RandBytes(ctx context.Context, in *RandBytesRequest, opts ...grpc.CallOption) (*RandBytesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RandBytesResponse)
	err := c.cc.Invoke(ctx, Rng_RandBytes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rngClient) RandIntegers(ctx context.Context, in *RandIntegersRequest, opts ...grpc.CallOption) (*RandIntegersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RandIntegersResponse)
	err := c.cc.Invoke(ctx, Rng_RandIntegers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rngClient) RandUniform(ctx context.Context, in *RandUniformRequest, opts ...grpc.CallOption) (*RandUniformResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RandUniformResponse)
	err := c.cc.Invoke(ctx, Rng_RandUniform_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rngClient) RandNormal(ctx context.Context, in *RandNormalRequest, opts ...grpc.CallOption) (*RandNormalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RandNormalResponse)
	err := c.cc.Invoke(ctx, Rng_RandNormal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rngClient) RandBooleansBiasAmplified(ctx context.Context, in *RandBooleansBiasAmplifiedRequest, opts ...grpc.CallOption) (*RandBooleansBiasAmplifiedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RandBooleansBiasAmplifiedResponse)
	err := c.cc.Invoke(ctx, Rng_RandBooleansBiasAmplified_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RngServer is the server API for Rng service.
// All implementations must embed UnimplementedRngServer
// for forward compatibility
type RngServer interface {
	RandBooleans(context.Context, *RandBooleansRequest) (*RandBooleansResponse, error)
	RandBytes(context.Context, *RandBytesRequest) (*RandBytesResponse, error)
	RandIntegers(context.Context, *RandIntegersRequest) (*RandIntegersResponse, error)
	RandUniform(context.Context, *RandUniformRequest) (*RandUniformResponse, error)
	RandNormal(context.Context, *RandNormalRequest) (*RandNormalResponse, error)
	RandBooleansBiasAmplified(context.Context, *RandBooleansBiasAmplifiedRequest) (*RandBooleansBiasAmplifiedResponse, error)
	mustEmbedUnimplementedRngServer()
}

// UnimplementedRngServer must be embedded to have forward compatible implementations.
type UnimplementedRngServer struct {
}

func (UnimplementedRngServer) RandBooleans(context.Context, *RandBooleansRequest) (*RandBooleansResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RandBooleans not implemented")
}
func (UnimplementedRngServer) RandBytes(context.Context, *RandBytesRequest) (*RandBytesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RandBytes not implemented")
}
func (UnimplementedRngServer) RandIntegers(context.Context, *RandIntegersRequest) (*RandIntegersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RandIntegers not implemented")
}
func (UnimplementedRngServer) RandUniform(context.Context, *RandUniformRequest) (*RandUniformResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RandUniform not implemented")
}
func (UnimplementedRngServer) RandNormal(context.Context, *RandNormalRequest) (*RandNormalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RandNormal not implemented")
}
func (UnimplementedRngServer) RandBooleansBiasAmplified(context.Context, *RandBooleansBiasAmplifiedRequest) (*RandBooleansBiasAmplifiedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RandBooleansBiasAmplified not implemented")
}
func (UnimplementedRngServer) mustEmbedUnimplementedRngServer() {}

// UnsafeRngServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RngServer will
// result in compilation errors.
type UnsafeRngServer interface {
	mustEmbedUnimplementedRngServer()
}

func RegisterRngServer(s grpc.ServiceRegistrar, srv RngServer) {
	s.RegisterService(&Rng_ServiceDesc, srv)
}

func _Rng_RandBooleans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RandBooleansRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RngServer).RandBooleans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rng_RandBooleans_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RngServer).RandBooleans(ctx, req.(*RandBooleansRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rng_RandBytes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RandBytesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RngServer).RandBytes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rng_RandBytes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RngServer).RandBytes(ctx, req.(*RandBytesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rng_RandIntegers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RandIntegersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RngServer).RandIntegers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rng_RandIntegers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RngServer).RandIntegers(ctx, req.(*RandIntegersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rng_RandUniform_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RandUniformRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RngServer).RandUniform(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rng_RandUniform_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RngServer).RandUniform(ctx, req.(*RandUniformRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rng_RandNormal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RandNormalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RngServer).RandNormal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rng_RandNormal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RngServer).RandNormal(ctx, req.(*RandNormalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rng_RandBooleansBiasAmplified_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RandBooleansBiasAmplifiedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RngServer).RandBooleansBiasAmplified(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rng_RandBooleansBiasAmplified_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RngServer).RandBooleansBiasAmplified(ctx, req.(*RandBooleansBiasAmplifiedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Rng_ServiceDesc is the grpc.ServiceDesc for Rng service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rng_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "psirng.Rng",
	HandlerType: (*RngServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RandBooleans",
			Handler:    _Rng_RandBooleans_Handler,
		},
		{
			MethodName: "RandBytes",
			Handler:    _Rng_RandBytes_Handler,
		},
		{
			MethodName: "RandIntegers",
			Handler:    _Rng_RandIntegers_Handler,
		},
		{
			MethodName: "RandUniform",
			Handler:    _Rng_RandUniform_Handler,
		},
		{
			MethodName: "RandNormal",
			Handler:    _Rng_RandNormal_Handler,
		},
		{
			MethodName: "RandBooleansBiasAmplified",
			Handler:    _Rng_RandBooleansBiasAmplified_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rng.proto",
}
